language: python
dist: bionic
python:
- '3.7'
services:
- docker
addons:
  apt:
    packages:
    - openjdk-11-jre-headless
before_install:
- openssl aes-256-cbc -K $encrypted_2a68b6131c57_key -iv $encrypted_2a68b6131c57_iv
  -in root_key.enc -out root_key -d
- sudo apt-get purge python2.7
- nvm install 6; nvm alias default node
- sudo useradd localstack -s /bin/bash
env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
  - BOTO_CONFIG=/dev/null
install:
- set -e
- PIP_CMD=pip3 VENV_OPTS="-p '`which python3`'" make install-basic
- make init
- nohup docker pull lambci/lambda:20191117-nodejs8.10 > /dev/null &
- nohup docker pull lambci/lambda:20191117-ruby2.5 > /dev/null &
- nohup docker pull lambci/lambda:20191117-python2.7 > /dev/null &
- nohup docker pull lambci/lambda:20191117-python3.6 > /dev/null &
- nohup docker pull lambci/lambda:20191117-dotnetcore2.0 > /dev/null &
- nohup docker pull lambci/lambda:dotnetcore3.1 > /dev/null &
- nohup docker pull lambci/lambda:20191117-provided > /dev/null &
- nohup docker pull lambci/lambda:java8 > /dev/null &
- nohup docker pull lambci/lambda:python3.8 > /dev/null &
before_script:
- bash test_mypy.sh
